//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPApp.IPService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IP", Namespace="http://schemas.datacontract.org/2004/07/IPService")]
    [System.SerializableAttribute()]
    public partial class IP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPService.IIPService")]
    public interface IIPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPService/InsertIP", ReplyAction="http://tempuri.org/IIPService/InsertIPResponse")]
        void InsertIP(IPApp.IPService.IP ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPService/InsertIP", ReplyAction="http://tempuri.org/IIPService/InsertIPResponse")]
        System.Threading.Tasks.Task InsertIPAsync(IPApp.IPService.IP ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPService/DeleteIP", ReplyAction="http://tempuri.org/IIPService/DeleteIPResponse")]
        void DeleteIP(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPService/DeleteIP", ReplyAction="http://tempuri.org/IIPService/DeleteIPResponse")]
        System.Threading.Tasks.Task DeleteIPAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPService/GetAllIPs", ReplyAction="http://tempuri.org/IIPService/GetAllIPsResponse")]
        IPApp.IPService.IP[] GetAllIPs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPService/GetAllIPs", ReplyAction="http://tempuri.org/IIPService/GetAllIPsResponse")]
        System.Threading.Tasks.Task<IPApp.IPService.IP[]> GetAllIPsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIPServiceChannel : IPApp.IPService.IIPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IPServiceClient : System.ServiceModel.ClientBase<IPApp.IPService.IIPService>, IPApp.IPService.IIPService {
        
        public IPServiceClient() {
        }
        
        public IPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertIP(IPApp.IPService.IP ip) {
            base.Channel.InsertIP(ip);
        }
        
        public System.Threading.Tasks.Task InsertIPAsync(IPApp.IPService.IP ip) {
            return base.Channel.InsertIPAsync(ip);
        }
        
        public void DeleteIP(int id) {
            base.Channel.DeleteIP(id);
        }
        
        public System.Threading.Tasks.Task DeleteIPAsync(int id) {
            return base.Channel.DeleteIPAsync(id);
        }
        
        public IPApp.IPService.IP[] GetAllIPs() {
            return base.Channel.GetAllIPs();
        }
        
        public System.Threading.Tasks.Task<IPApp.IPService.IP[]> GetAllIPsAsync() {
            return base.Channel.GetAllIPsAsync();
        }
    }
}
