<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="IPApp._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <table>
        <tr>
            <td style="text-align: right">Name</td>
            <td>
                <asp:TextBox ID="TextBoxName" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td style="text-align: right">IP</td>
            <td>
                <asp:TextBox ID="TextBoxAddress" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <asp:Button ID="ButtonAdd" runat="server" OnClick="ButtonAdd_Click" Text="Save"/>
            </td>
        </tr>
    </table>

    <p>
        <asp:GridView ID="GridViewIPs" runat="server" AllowPaging="True"  DataKeyNames="ID,Name,Address"
            AllowSorting="True" AutoGenerateDeleteButton="True" 
            onrowdeleting="GridViewIPs_Delete"
          >
        </asp:GridView>
</p>

</asp:Content>
